spring:
  application:
    name: userService

  config:
    import: optional:file:../.env

  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/lakepop_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

  jwt:
    token:
      lifetime: ${JWT_LIFETIME:1h}
      signing-key: ${JWT_SECRET_KEY:c2FqaGdkSllBU1VZZHV5eXVzYWRnYW9pdXNkaGl1Kyst}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
