spring:
  application:
    name: userService

  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/lakepop_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8081